name: actions
description: Setup Nitric CLI on GitHub Actions runners
inputs:
  version: 
    description: Version of the CLI being used e.g. 1.2.1
    required: false
    default: 1.2.1    
runs:
  using: node12
  main: dist/index.js